name: "Build"

on:
  push:
  workflow_dispatch:
    inputs:
      nixpkgs-patch:
        required: true
        type: boolean
        default: false
      package:
        required: true
        type: string


jobs:
  build-nur:
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.package == '')
    strategy:
        matrix:
          package: [catspeak, mixbot, smoos-bot, smoos-cs, website]
    uses: ./.github/workflows/cache.yml
    secrets: inherit
    with:
      nixpkgs-patch: false
      nur: true
      package: ${{ matrix.package }}

  buid-pkg:
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.package != ''
    uses: ./.github/workflows/cache.yml
    secrets: inherit
    with:
      nixpkgs-patch: ${{ inputs.nixpkgs-patch }}
      nur: false
      package: ${{ inputs.package }}
