name: "Build"

on:
  push:
  workflow_dispatch:
    inputs:
      nixpkgs-patch:
        required: true
        type: boolean
        default: false
      package:
        required: true
        type: string


jobs:
  build-nur:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == "workflow_dispatch" && github.event.inputs.package == '')
    uses: ./.github/workflows/cache.yml
    strategy:
      matrix:
        package: [catspeak, mixbot, smoos-bot, smoos-cs, website]
    with:
      nixpkgs-patch: false
      package: ${{ matrix.package }}

  buid-pkg:
    runs-on: ubuntu-latest
    if: github.event_name == "workflow_dispatch" && github.event.inputs.package != ''
    uses: ./.github/workflows/cache.yml
    with:
      nixpkgs-patch: ${{ inputs.nixpkgs-patch }}
      package: ${{ inputs.package }}
