name: "Cache"

on:
  push:
  workflow_dispatch:

jobs:
  cache:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: schwegelbin
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: |
        nix-build -A catspeak
        nix-build -A smoos-bot
        #nix-build -A smoos-cs
        #nix-build -A smoos-rs
