name: "Cache"

on:
  workflow_call:
    inputs:
      nixpkgs-patch:
        required: true
        type: boolean
      nur:
        required: true
        type: boolean
      package:
        required: true
        type: string
    secrets:
      CACHIX_AUTH_TOKEN:
        required: true


jobs:
  cache:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Patch nixpkgs
      if: ${{ inputs.nixpkgs-patch }}
      run: |
        nix-channel --add https://github.com/SchweGELBin/nixpkgs/archive/refs/heads/nixos-unstable.tar.gz nixos-unstable
        nix-channel --update
    - uses: cachix/cachix-action@v14
      with:
        name: schwegelbin
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-build -A ${{ inputs.package }}
      if: ${{ inputs.nur }}
    - run: nix-shell -p ${{ inputs.package }}
      if: ${{ !inputs.nur }}
