name: "Cache"

on:
  push:
  workflow_dispatch:
    inputs:
      package:
        required: true
        type: string


jobs:
  nur:
    runs-on: ${{ matrix.os }}
    if: github.event_name == 'push'
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
        package: [catspeak, mixbot, smoos-bot, smoos-cs, website]
    steps:
    - uses: actions/checkout@v4
    - name: Checkout nixpkgs
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: schwegelbin
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-build -A ${{ matrix.package }}

  package:
    runs-on: ${{ matrix.os }}
    if: github.event_name == 'workflow_dispatch'
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
    steps:
    - name: Checkout nixpkgs
      with:
        repository: SchweGELBin/nixpkgs
        ref: nixos-unstable
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: schwegelbin
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      run: nix-build -A ${{ inputs.package }}
