name: "Cache"

on:
  push:
  workflow_dispatch:

jobs:
  cache:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pkgs: [catspeak, smoos-bot, smoos-cs]
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: schwegelbin
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-build --arg crossSystem '{ config = "aarch64-unknown-linux-gnu"; }' -A ${{ matrix.pkgs }}
